### ISSUE TITLE
Typo in lib/common.php

### ISSUE THREAD

**Issue by spencerbyw** [halfer/php-tutorial-project#1]
On line 34 of the comments in lib/common.php, the last word says "acccess" (3 c's). This should be changed to "access" (2 c's).
UPDATE: Submitted a pull request to resolve it.

**Comment by halfer** [comment]
Hi @spencerbyw, thanks! Well spotted.

I'll try to get that merged and published in the week.

**Comment by halfer** [comment]
This change was merged.

Update: the changes should have been rebased into existing commits, not merely merged into the repo; my bad. I have done that now for text versions v4 and v5, and it will go out shortly.
